FROM postgres:9.4-alpine
# Camunda is currently supported on PostgreSQL 9.4.
# See also: https://docs.camunda.org/manual/latest/introduction/supported-environments/

COPY *.sql /docker-entrypoint-initdb.d/