/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.openapi.client.model;

import com.camunda.consulting.openapi.client.model.IdentityServiceGroupDto;
import com.camunda.consulting.openapi.client.model.IdentityServiceUserDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IdentityServiceGroupInfoDto
 */
public class IdentityServiceGroupInfoDtoTest {
    private final IdentityServiceGroupInfoDto model = new IdentityServiceGroupInfoDto();

    /**
     * Model tests for IdentityServiceGroupInfoDto
     */
    @Test
    public void testIdentityServiceGroupInfoDto() {
        // TODO: test IdentityServiceGroupInfoDto
    }

    /**
     * Test the property 'groups'
     */
    @Test
    public void groupsTest() {
        // TODO: test groups
    }

    /**
     * Test the property 'groupUsers'
     */
    @Test
    public void groupUsersTest() {
        // TODO: test groupUsers
    }

}
