/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.openapi.client.model;

import com.camunda.consulting.openapi.client.model.HandleExternalTaskDto;
import com.camunda.consulting.openapi.client.model.LockExternalTaskDtoAllOf;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LockExternalTaskDto
 */
public class LockExternalTaskDtoTest {
    private final LockExternalTaskDto model = new LockExternalTaskDto();

    /**
     * Model tests for LockExternalTaskDto
     */
    @Test
    public void testLockExternalTaskDto() {
        // TODO: test LockExternalTaskDto
    }

    /**
     * Test the property 'lockDuration'
     */
    @Test
    public void lockDurationTest() {
        // TODO: test lockDuration
    }

    /**
     * Test the property 'workerId'
     */
    @Test
    public void workerIdTest() {
        // TODO: test workerId
    }

}
