/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.openapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ExternalTaskFailureDto
 */
public class ExternalTaskFailureDtoTest {
    private final ExternalTaskFailureDto model = new ExternalTaskFailureDto();

    /**
     * Model tests for ExternalTaskFailureDto
     */
    @Test
    public void testExternalTaskFailureDto() {
        // TODO: test ExternalTaskFailureDto
    }

    /**
     * Test the property 'workerId'
     */
    @Test
    public void workerIdTest() {
        // TODO: test workerId
    }

    /**
     * Test the property 'errorMessage'
     */
    @Test
    public void errorMessageTest() {
        // TODO: test errorMessage
    }

    /**
     * Test the property 'errorDetails'
     */
    @Test
    public void errorDetailsTest() {
        // TODO: test errorDetails
    }

    /**
     * Test the property 'retries'
     */
    @Test
    public void retriesTest() {
        // TODO: test retries
    }

    /**
     * Test the property 'retryTimeout'
     */
    @Test
    public void retryTimeoutTest() {
        // TODO: test retryTimeout
    }

}
