/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.openapi.client.model;

import com.camunda.consulting.openapi.client.model.ExecutionDto;
import com.camunda.consulting.openapi.client.model.ProcessInstanceDto;
import com.camunda.consulting.openapi.client.model.VariableValueDto;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MessageCorrelationResultWithVariableDto
 */
public class MessageCorrelationResultWithVariableDtoTest {
    private final MessageCorrelationResultWithVariableDto model = new MessageCorrelationResultWithVariableDto();

    /**
     * Model tests for MessageCorrelationResultWithVariableDto
     */
    @Test
    public void testMessageCorrelationResultWithVariableDto() {
        // TODO: test MessageCorrelationResultWithVariableDto
    }

    /**
     * Test the property 'resultType'
     */
    @Test
    public void resultTypeTest() {
        // TODO: test resultType
    }

    /**
     * Test the property 'processInstance'
     */
    @Test
    public void processInstanceTest() {
        // TODO: test processInstance
    }

    /**
     * Test the property 'execution'
     */
    @Test
    public void executionTest() {
        // TODO: test execution
    }

    /**
     * Test the property 'variables'
     */
    @Test
    public void variablesTest() {
        // TODO: test variables
    }

}
