export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'

export const PROCESS_DEFINITION_REQUEST = 'PROCESS_DEFINITION_REQUEST'
export const PROCESS_DEFINITION_SUCCESS = 'PROCESS_DEFINITION_SUCCESS'
export const PROCESS_DEFINITION_FAILURE = 'PROCESS_DEFINITION_FAILURE'

export const PROCESS_DEFINITION_XML_REQUEST = 'PROCESS_DEFINITION_XML_REQUEST'
export const PROCESS_DEFINITION_XML_SUCCESS = 'PROCESS_DEFINITION_XML_SUCCESS'
export const PROCESS_DEFINITION_XML_FAILURE = 'PROCESS_DEFINITION_XML_FAILURE'

export const NEW_PROCESS_INSTANCE_REQUEST = 'NEW_PROCESS_INSTANCE_REQUEST'
export const NEW_PROCESS_INSTANCE_SUCCESS = 'NEW_PROCESS_INSTANCE_SUCCESS'
export const NEW_PROCESS_INSTANCE_FAILURE = 'NEW_PROCESS_INSTANCE_FAILURE'

export const FORM_KEY_REQUEST = 'FORM_KEY_REQUEST'
export const FORM_KEY_SUCCESS = 'FORM_KEY_SUCCESS'
export const FORM_KEY_FAILURE = 'FORM_KEY_FAILURE'

export const TASKS_REQUEST = 'TASKS_REQUEST'
export const TASKS_SUCCESS = 'TASKS_SUCCESS'
export const TASKS_FAILURE = 'TASKS_FAILURE'

export const TASK_FORM_KEY_REQUEST = 'TASK_FORM_KEY_REQUEST'
export const TASK_FORM_KEY_SUCCESS = 'TASK_FORM_KEY_SUCCESS'
export const TASK_FORM_KEY_FAILURE = 'TASK_FORM_KEY_FAILURE'

export const TASK_SUBMITTED_REQUEST = 'TASK_SUBMITTED_REQUEST'
export const TASK_SUBMITTED_SUCCESS = 'TASK_SUBMITTED_SUCCESS'
export const TASK_SUBMITTED_FAILURE = 'TASK_SUBMITTED_FAILURE'

export const TASK_VARIABLES_REQUEST = 'TASK_VARIABLES_REQUEST'
export const TASK_VARIABLES_SUCCESS = 'TASK_VARIABLES_SUCCESS'
export const TASK_VARIABLES_FAILURE = 'TASK_VARIABLES_FAILURE'

export const PROCESS_DEPLOYMENT_REQUEST = 'PROCESS_DEPLOYMENT_REQUEST'
export const PROCESS_DEPLOYMENT_SUCCESS = 'PROCESS_DEPLOYMENT_SUCCESS'
export const PROCESS_DEPLOYMENT_FAILURE = 'PROCESS_DEPLOYMENT_FAILURE'
