export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'

export const STARGAZERS_REQUEST = 'STARGAZERS_REQUEST'
export const STARGAZERS_SUCCESS = 'STARGAZERS_SUCCESS'
export const STARGAZERS_FAILURE = 'STARGAZERS_FAILURE'

export const PROCESS_DEFINITION_REQUEST = 'PROCESS_DEFINITION_REQUEST'
export const PROCESS_DEFINITION_SUCCESS = 'PROCESS_DEFINITION_SUCCESS'
export const PROCESS_DEFINITION_FAILURE = 'PROCESS_DEFINITION_FAILURE'

export const NEW_PROCESS_INSTANCE_REQUEST = 'NEW_PROCESS_INSTANCE_REQUEST'
export const NEW_PROCESS_INSTANCE_SUCCESS = 'NEW_PROCESS_INSTANCE_SUCCESS'
export const NEW_PROCESS_INSTANCE_FAILURE = 'NEW_PROCESS_INSTANCE_FAILURE'

export const FORM_KEY_REQUEST = 'FORM_KEY_REQUEST'
export const FORM_KEY_SUCCESS = 'FORM_KEY_SUCCESS'
export const FORM_KEY_FAILURE = 'FORM_KEY_FAILURE'

export const TASK_SUBMITTED_REQUEST = 'TASK_SUBMITTED_REQUEST'
export const TASK_SUBMITTED_SUCCESS = 'TASK_SUBMITTED_SUCCESS'
export const TASK_SUBMITTED_FAILURE = 'TASK_SUBMITTED_FAILURE'
