/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.openapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AuthorizationCheckResultDto
 */
@JsonPropertyOrder({
  AuthorizationCheckResultDto.JSON_PROPERTY_PERMISSION_NAME,
  AuthorizationCheckResultDto.JSON_PROPERTY_RESOURCE_NAME,
  AuthorizationCheckResultDto.JSON_PROPERTY_RESOURCE_ID,
  AuthorizationCheckResultDto.JSON_PROPERTY_IS_AUTHORIZED
})
@JsonTypeName("AuthorizationCheckResultDto")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-13T16:56:52.297572+02:00[Europe/Berlin]")
public class AuthorizationCheckResultDto {
  public static final String JSON_PROPERTY_PERMISSION_NAME = "permissionName";
  private JsonNullable<String> permissionName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_RESOURCE_NAME = "resourceName";
  private JsonNullable<String> resourceName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_RESOURCE_ID = "resourceId";
  private JsonNullable<String> resourceId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_IS_AUTHORIZED = "isAuthorized";
  private JsonNullable<Boolean> isAuthorized = JsonNullable.<Boolean>undefined();


  public AuthorizationCheckResultDto permissionName(String permissionName) {
    this.permissionName = JsonNullable.<String>of(permissionName);
    
    return this;
  }

   /**
   * Name of the permission which was checked.
   * @return permissionName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the permission which was checked.")
  @JsonIgnore

  public String getPermissionName() {
        return permissionName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PERMISSION_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPermissionName_JsonNullable() {
    return permissionName;
  }
  
  @JsonProperty(JSON_PROPERTY_PERMISSION_NAME)
  public void setPermissionName_JsonNullable(JsonNullable<String> permissionName) {
    this.permissionName = permissionName;
  }

  public void setPermissionName(String permissionName) {
    this.permissionName = JsonNullable.<String>of(permissionName);
  }


  public AuthorizationCheckResultDto resourceName(String resourceName) {
    this.resourceName = JsonNullable.<String>of(resourceName);
    
    return this;
  }

   /**
   * The name of the resource for which the permission check was performed.
   * @return resourceName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the resource for which the permission check was performed.")
  @JsonIgnore

  public String getResourceName() {
        return resourceName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RESOURCE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getResourceName_JsonNullable() {
    return resourceName;
  }
  
  @JsonProperty(JSON_PROPERTY_RESOURCE_NAME)
  public void setResourceName_JsonNullable(JsonNullable<String> resourceName) {
    this.resourceName = resourceName;
  }

  public void setResourceName(String resourceName) {
    this.resourceName = JsonNullable.<String>of(resourceName);
  }


  public AuthorizationCheckResultDto resourceId(String resourceId) {
    this.resourceId = JsonNullable.<String>of(resourceId);
    
    return this;
  }

   /**
   * The id of the resource for which the permission check was performed.
   * @return resourceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The id of the resource for which the permission check was performed.")
  @JsonIgnore

  public String getResourceId() {
        return resourceId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RESOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getResourceId_JsonNullable() {
    return resourceId;
  }
  
  @JsonProperty(JSON_PROPERTY_RESOURCE_ID)
  public void setResourceId_JsonNullable(JsonNullable<String> resourceId) {
    this.resourceId = resourceId;
  }

  public void setResourceId(String resourceId) {
    this.resourceId = JsonNullable.<String>of(resourceId);
  }


  public AuthorizationCheckResultDto isAuthorized(Boolean isAuthorized) {
    this.isAuthorized = JsonNullable.<Boolean>of(isAuthorized);
    
    return this;
  }

   /**
   * True / false for isAuthorized.
   * @return isAuthorized
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "True / false for isAuthorized.")
  @JsonIgnore

  public Boolean getIsAuthorized() {
        return isAuthorized.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_IS_AUTHORIZED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getIsAuthorized_JsonNullable() {
    return isAuthorized;
  }
  
  @JsonProperty(JSON_PROPERTY_IS_AUTHORIZED)
  public void setIsAuthorized_JsonNullable(JsonNullable<Boolean> isAuthorized) {
    this.isAuthorized = isAuthorized;
  }

  public void setIsAuthorized(Boolean isAuthorized) {
    this.isAuthorized = JsonNullable.<Boolean>of(isAuthorized);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizationCheckResultDto authorizationCheckResultDto = (AuthorizationCheckResultDto) o;
    return Objects.equals(this.permissionName, authorizationCheckResultDto.permissionName) &&
        Objects.equals(this.resourceName, authorizationCheckResultDto.resourceName) &&
        Objects.equals(this.resourceId, authorizationCheckResultDto.resourceId) &&
        Objects.equals(this.isAuthorized, authorizationCheckResultDto.isAuthorized);
  }

  @Override
  public int hashCode() {
    return Objects.hash(permissionName, resourceName, resourceId, isAuthorized);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizationCheckResultDto {\n");
    sb.append("    permissionName: ").append(toIndentedString(permissionName)).append("\n");
    sb.append("    resourceName: ").append(toIndentedString(resourceName)).append("\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    isAuthorized: ").append(toIndentedString(isAuthorized)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

