/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.openapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.camunda.consulting.openapi.client.model.HistoricProcessInstanceQueryDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DeleteHistoricProcessInstancesDto
 */
@JsonPropertyOrder({
  DeleteHistoricProcessInstancesDto.JSON_PROPERTY_HISTORIC_PROCESS_INSTANCE_IDS,
  DeleteHistoricProcessInstancesDto.JSON_PROPERTY_HISTORIC_PROCESS_INSTANCE_QUERY,
  DeleteHistoricProcessInstancesDto.JSON_PROPERTY_DELETE_REASON,
  DeleteHistoricProcessInstancesDto.JSON_PROPERTY_FAIL_IF_NOT_EXISTS
})
@JsonTypeName("DeleteHistoricProcessInstancesDto")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-13T16:56:52.297572+02:00[Europe/Berlin]")
public class DeleteHistoricProcessInstancesDto {
  public static final String JSON_PROPERTY_HISTORIC_PROCESS_INSTANCE_IDS = "historicProcessInstanceIds";
  private JsonNullable<List<String>> historicProcessInstanceIds = JsonNullable.<List<String>>undefined();

  public static final String JSON_PROPERTY_HISTORIC_PROCESS_INSTANCE_QUERY = "historicProcessInstanceQuery";
  private HistoricProcessInstanceQueryDto historicProcessInstanceQuery;

  public static final String JSON_PROPERTY_DELETE_REASON = "deleteReason";
  private JsonNullable<String> deleteReason = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_FAIL_IF_NOT_EXISTS = "failIfNotExists";
  private JsonNullable<Boolean> failIfNotExists = JsonNullable.<Boolean>undefined();


  public DeleteHistoricProcessInstancesDto historicProcessInstanceIds(List<String> historicProcessInstanceIds) {
    this.historicProcessInstanceIds = JsonNullable.<List<String>>of(historicProcessInstanceIds);
    
    return this;
  }

  public DeleteHistoricProcessInstancesDto addHistoricProcessInstanceIdsItem(String historicProcessInstanceIdsItem) {
    if (this.historicProcessInstanceIds == null || !this.historicProcessInstanceIds.isPresent()) {
      this.historicProcessInstanceIds = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.historicProcessInstanceIds.get().add(historicProcessInstanceIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

   /**
   * A list historic process instance ids to delete.
   * @return historicProcessInstanceIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list historic process instance ids to delete.")
  @JsonIgnore

  public List<String> getHistoricProcessInstanceIds() {
        return historicProcessInstanceIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_HISTORIC_PROCESS_INSTANCE_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getHistoricProcessInstanceIds_JsonNullable() {
    return historicProcessInstanceIds;
  }
  
  @JsonProperty(JSON_PROPERTY_HISTORIC_PROCESS_INSTANCE_IDS)
  public void setHistoricProcessInstanceIds_JsonNullable(JsonNullable<List<String>> historicProcessInstanceIds) {
    this.historicProcessInstanceIds = historicProcessInstanceIds;
  }

  public void setHistoricProcessInstanceIds(List<String> historicProcessInstanceIds) {
    this.historicProcessInstanceIds = JsonNullable.<List<String>>of(historicProcessInstanceIds);
  }


  public DeleteHistoricProcessInstancesDto historicProcessInstanceQuery(HistoricProcessInstanceQueryDto historicProcessInstanceQuery) {
    
    this.historicProcessInstanceQuery = historicProcessInstanceQuery;
    return this;
  }

   /**
   * Get historicProcessInstanceQuery
   * @return historicProcessInstanceQuery
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HISTORIC_PROCESS_INSTANCE_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HistoricProcessInstanceQueryDto getHistoricProcessInstanceQuery() {
    return historicProcessInstanceQuery;
  }


  public void setHistoricProcessInstanceQuery(HistoricProcessInstanceQueryDto historicProcessInstanceQuery) {
    this.historicProcessInstanceQuery = historicProcessInstanceQuery;
  }


  public DeleteHistoricProcessInstancesDto deleteReason(String deleteReason) {
    this.deleteReason = JsonNullable.<String>of(deleteReason);
    
    return this;
  }

   /**
   * A string with delete reason.
   * @return deleteReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A string with delete reason.")
  @JsonIgnore

  public String getDeleteReason() {
        return deleteReason.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DELETE_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDeleteReason_JsonNullable() {
    return deleteReason;
  }
  
  @JsonProperty(JSON_PROPERTY_DELETE_REASON)
  public void setDeleteReason_JsonNullable(JsonNullable<String> deleteReason) {
    this.deleteReason = deleteReason;
  }

  public void setDeleteReason(String deleteReason) {
    this.deleteReason = JsonNullable.<String>of(deleteReason);
  }


  public DeleteHistoricProcessInstancesDto failIfNotExists(Boolean failIfNotExists) {
    this.failIfNotExists = JsonNullable.<Boolean>of(failIfNotExists);
    
    return this;
  }

   /**
   * If set to &#x60;false&#x60;, the request will still be successful if one ore more of the process ids are not found.
   * @return failIfNotExists
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If set to `false`, the request will still be successful if one ore more of the process ids are not found.")
  @JsonIgnore

  public Boolean getFailIfNotExists() {
        return failIfNotExists.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FAIL_IF_NOT_EXISTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getFailIfNotExists_JsonNullable() {
    return failIfNotExists;
  }
  
  @JsonProperty(JSON_PROPERTY_FAIL_IF_NOT_EXISTS)
  public void setFailIfNotExists_JsonNullable(JsonNullable<Boolean> failIfNotExists) {
    this.failIfNotExists = failIfNotExists;
  }

  public void setFailIfNotExists(Boolean failIfNotExists) {
    this.failIfNotExists = JsonNullable.<Boolean>of(failIfNotExists);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteHistoricProcessInstancesDto deleteHistoricProcessInstancesDto = (DeleteHistoricProcessInstancesDto) o;
    return Objects.equals(this.historicProcessInstanceIds, deleteHistoricProcessInstancesDto.historicProcessInstanceIds) &&
        Objects.equals(this.historicProcessInstanceQuery, deleteHistoricProcessInstancesDto.historicProcessInstanceQuery) &&
        Objects.equals(this.deleteReason, deleteHistoricProcessInstancesDto.deleteReason) &&
        Objects.equals(this.failIfNotExists, deleteHistoricProcessInstancesDto.failIfNotExists);
  }

  @Override
  public int hashCode() {
    return Objects.hash(historicProcessInstanceIds, historicProcessInstanceQuery, deleteReason, failIfNotExists);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteHistoricProcessInstancesDto {\n");
    sb.append("    historicProcessInstanceIds: ").append(toIndentedString(historicProcessInstanceIds)).append("\n");
    sb.append("    historicProcessInstanceQuery: ").append(toIndentedString(historicProcessInstanceQuery)).append("\n");
    sb.append("    deleteReason: ").append(toIndentedString(deleteReason)).append("\n");
    sb.append("    failIfNotExists: ").append(toIndentedString(failIfNotExists)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

