/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.openapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.camunda.consulting.openapi.client.model.MigrationInstructionValidationReportDto;
import com.camunda.consulting.openapi.client.model.MigrationVariableValidationReportDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * MigrationPlanReportDto
 */
@JsonPropertyOrder({
  MigrationPlanReportDto.JSON_PROPERTY_INSTRUCTION_REPORTS,
  MigrationPlanReportDto.JSON_PROPERTY_VARIABLE_REPORTS
})
@JsonTypeName("MigrationPlanReportDto")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-13T17:49:51.183809+02:00[Europe/Berlin]")
public class MigrationPlanReportDto {
  public static final String JSON_PROPERTY_INSTRUCTION_REPORTS = "instructionReports";
  private List<MigrationInstructionValidationReportDto> instructionReports = null;

  public static final String JSON_PROPERTY_VARIABLE_REPORTS = "variableReports";
  private Map<String, MigrationVariableValidationReportDto> variableReports = null;


  public MigrationPlanReportDto instructionReports(List<MigrationInstructionValidationReportDto> instructionReports) {
    
    this.instructionReports = instructionReports;
    return this;
  }

  public MigrationPlanReportDto addInstructionReportsItem(MigrationInstructionValidationReportDto instructionReportsItem) {
    if (this.instructionReports == null) {
      this.instructionReports = new ArrayList<>();
    }
    this.instructionReports.add(instructionReportsItem);
    return this;
  }

   /**
   * The list of instruction validation reports. If no validation errors are detected it is an empty list.
   * @return instructionReports
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The list of instruction validation reports. If no validation errors are detected it is an empty list.")
  @JsonProperty(JSON_PROPERTY_INSTRUCTION_REPORTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MigrationInstructionValidationReportDto> getInstructionReports() {
    return instructionReports;
  }


  public void setInstructionReports(List<MigrationInstructionValidationReportDto> instructionReports) {
    this.instructionReports = instructionReports;
  }


  public MigrationPlanReportDto variableReports(Map<String, MigrationVariableValidationReportDto> variableReports) {
    
    this.variableReports = variableReports;
    return this;
  }

  public MigrationPlanReportDto putVariableReportsItem(String key, MigrationVariableValidationReportDto variableReportsItem) {
    if (this.variableReports == null) {
      this.variableReports = new HashMap<>();
    }
    this.variableReports.put(key, variableReportsItem);
    return this;
  }

   /**
   * A map of variable reports. Each key is a variable name and each value a JSON object consisting of the variable&#39;s type, value, value info object and a list of failures.
   * @return variableReports
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A map of variable reports. Each key is a variable name and each value a JSON object consisting of the variable's type, value, value info object and a list of failures.")
  @JsonProperty(JSON_PROPERTY_VARIABLE_REPORTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, MigrationVariableValidationReportDto> getVariableReports() {
    return variableReports;
  }


  public void setVariableReports(Map<String, MigrationVariableValidationReportDto> variableReports) {
    this.variableReports = variableReports;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MigrationPlanReportDto migrationPlanReportDto = (MigrationPlanReportDto) o;
    return Objects.equals(this.instructionReports, migrationPlanReportDto.instructionReports) &&
        Objects.equals(this.variableReports, migrationPlanReportDto.variableReports);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instructionReports, variableReports);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MigrationPlanReportDto {\n");
    sb.append("    instructionReports: ").append(toIndentedString(instructionReports)).append("\n");
    sb.append("    variableReports: ").append(toIndentedString(variableReports)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

