/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.openapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.camunda.consulting.openapi.client.model.MigrationInstructionDto;
import com.camunda.consulting.openapi.client.model.VariableValueDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * MigrationPlanDto
 */
@JsonPropertyOrder({
  MigrationPlanDto.JSON_PROPERTY_SOURCE_PROCESS_DEFINITION_ID,
  MigrationPlanDto.JSON_PROPERTY_TARGET_PROCESS_DEFINITION_ID,
  MigrationPlanDto.JSON_PROPERTY_INSTRUCTIONS,
  MigrationPlanDto.JSON_PROPERTY_VARIABLES
})
@JsonTypeName("MigrationPlanDto")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-13T16:56:52.297572+02:00[Europe/Berlin]")
public class MigrationPlanDto {
  public static final String JSON_PROPERTY_SOURCE_PROCESS_DEFINITION_ID = "sourceProcessDefinitionId";
  private JsonNullable<String> sourceProcessDefinitionId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TARGET_PROCESS_DEFINITION_ID = "targetProcessDefinitionId";
  private JsonNullable<String> targetProcessDefinitionId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_INSTRUCTIONS = "instructions";
  private JsonNullable<List<MigrationInstructionDto>> instructions = JsonNullable.<List<MigrationInstructionDto>>undefined();

  public static final String JSON_PROPERTY_VARIABLES = "variables";
  private JsonNullable<Map<String, VariableValueDto>> variables = JsonNullable.<Map<String, VariableValueDto>>undefined();


  public MigrationPlanDto sourceProcessDefinitionId(String sourceProcessDefinitionId) {
    this.sourceProcessDefinitionId = JsonNullable.<String>of(sourceProcessDefinitionId);
    
    return this;
  }

   /**
   * The id of the source process definition for the migration.
   * @return sourceProcessDefinitionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The id of the source process definition for the migration.")
  @JsonIgnore

  public String getSourceProcessDefinitionId() {
        return sourceProcessDefinitionId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SOURCE_PROCESS_DEFINITION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSourceProcessDefinitionId_JsonNullable() {
    return sourceProcessDefinitionId;
  }
  
  @JsonProperty(JSON_PROPERTY_SOURCE_PROCESS_DEFINITION_ID)
  public void setSourceProcessDefinitionId_JsonNullable(JsonNullable<String> sourceProcessDefinitionId) {
    this.sourceProcessDefinitionId = sourceProcessDefinitionId;
  }

  public void setSourceProcessDefinitionId(String sourceProcessDefinitionId) {
    this.sourceProcessDefinitionId = JsonNullable.<String>of(sourceProcessDefinitionId);
  }


  public MigrationPlanDto targetProcessDefinitionId(String targetProcessDefinitionId) {
    this.targetProcessDefinitionId = JsonNullable.<String>of(targetProcessDefinitionId);
    
    return this;
  }

   /**
   * The id of the target process definition for the migration.
   * @return targetProcessDefinitionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The id of the target process definition for the migration.")
  @JsonIgnore

  public String getTargetProcessDefinitionId() {
        return targetProcessDefinitionId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TARGET_PROCESS_DEFINITION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTargetProcessDefinitionId_JsonNullable() {
    return targetProcessDefinitionId;
  }
  
  @JsonProperty(JSON_PROPERTY_TARGET_PROCESS_DEFINITION_ID)
  public void setTargetProcessDefinitionId_JsonNullable(JsonNullable<String> targetProcessDefinitionId) {
    this.targetProcessDefinitionId = targetProcessDefinitionId;
  }

  public void setTargetProcessDefinitionId(String targetProcessDefinitionId) {
    this.targetProcessDefinitionId = JsonNullable.<String>of(targetProcessDefinitionId);
  }


  public MigrationPlanDto instructions(List<MigrationInstructionDto> instructions) {
    this.instructions = JsonNullable.<List<MigrationInstructionDto>>of(instructions);
    
    return this;
  }

  public MigrationPlanDto addInstructionsItem(MigrationInstructionDto instructionsItem) {
    if (this.instructions == null || !this.instructions.isPresent()) {
      this.instructions = JsonNullable.<List<MigrationInstructionDto>>of(new ArrayList<>());
    }
    try {
      this.instructions.get().add(instructionsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

   /**
   * A list of migration instructions which map equal activities. Each migration instruction is a JSON object with the following properties:
   * @return instructions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of migration instructions which map equal activities. Each migration instruction is a JSON object with the following properties:")
  @JsonIgnore

  public List<MigrationInstructionDto> getInstructions() {
        return instructions.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<MigrationInstructionDto>> getInstructions_JsonNullable() {
    return instructions;
  }
  
  @JsonProperty(JSON_PROPERTY_INSTRUCTIONS)
  public void setInstructions_JsonNullable(JsonNullable<List<MigrationInstructionDto>> instructions) {
    this.instructions = instructions;
  }

  public void setInstructions(List<MigrationInstructionDto> instructions) {
    this.instructions = JsonNullable.<List<MigrationInstructionDto>>of(instructions);
  }


  public MigrationPlanDto variables(Map<String, VariableValueDto> variables) {
    this.variables = JsonNullable.<Map<String, VariableValueDto>>of(variables);
    
    return this;
  }

  public MigrationPlanDto putVariablesItem(String key, VariableValueDto variablesItem) {
    if (this.variables == null || !this.variables.isPresent()) {
      this.variables = JsonNullable.<Map<String, VariableValueDto>>of(new HashMap<>());
    }
    try {
      this.variables.get().put(key, variablesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

   /**
   * A map of variables which will be set into the process instances&#39; scope. Each key is a variable name and each value a JSON variable value object.
   * @return variables
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A map of variables which will be set into the process instances' scope. Each key is a variable name and each value a JSON variable value object.")
  @JsonIgnore

  public Map<String, VariableValueDto> getVariables() {
        return variables.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VARIABLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, VariableValueDto>> getVariables_JsonNullable() {
    return variables;
  }
  
  @JsonProperty(JSON_PROPERTY_VARIABLES)
  public void setVariables_JsonNullable(JsonNullable<Map<String, VariableValueDto>> variables) {
    this.variables = variables;
  }

  public void setVariables(Map<String, VariableValueDto> variables) {
    this.variables = JsonNullable.<Map<String, VariableValueDto>>of(variables);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MigrationPlanDto migrationPlanDto = (MigrationPlanDto) o;
    return Objects.equals(this.sourceProcessDefinitionId, migrationPlanDto.sourceProcessDefinitionId) &&
        Objects.equals(this.targetProcessDefinitionId, migrationPlanDto.targetProcessDefinitionId) &&
        Objects.equals(this.instructions, migrationPlanDto.instructions) &&
        Objects.equals(this.variables, migrationPlanDto.variables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceProcessDefinitionId, targetProcessDefinitionId, instructions, variables);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MigrationPlanDto {\n");
    sb.append("    sourceProcessDefinitionId: ").append(toIndentedString(sourceProcessDefinitionId)).append("\n");
    sb.append("    targetProcessDefinitionId: ").append(toIndentedString(targetProcessDefinitionId)).append("\n");
    sb.append("    instructions: ").append(toIndentedString(instructions)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

