/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.openapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * MigrationVariableValidationReportDtoAllOf
 */
@JsonPropertyOrder({
  MigrationVariableValidationReportDtoAllOf.JSON_PROPERTY_FAILURES
})
@JsonTypeName("MigrationVariableValidationReportDto_allOf")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-13T16:56:52.297572+02:00[Europe/Berlin]")
public class MigrationVariableValidationReportDtoAllOf {
  public static final String JSON_PROPERTY_FAILURES = "failures";
  private JsonNullable<List<String>> failures = JsonNullable.<List<String>>undefined();


  public MigrationVariableValidationReportDtoAllOf failures(List<String> failures) {
    this.failures = JsonNullable.<List<String>>of(failures);
    
    return this;
  }

  public MigrationVariableValidationReportDtoAllOf addFailuresItem(String failuresItem) {
    if (this.failures == null || !this.failures.isPresent()) {
      this.failures = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.failures.get().add(failuresItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

   /**
   * A list of variable validation report messages.
   * @return failures
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of variable validation report messages.")
  @JsonIgnore

  public List<String> getFailures() {
        return failures.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FAILURES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getFailures_JsonNullable() {
    return failures;
  }
  
  @JsonProperty(JSON_PROPERTY_FAILURES)
  public void setFailures_JsonNullable(JsonNullable<List<String>> failures) {
    this.failures = failures;
  }

  public void setFailures(List<String> failures) {
    this.failures = JsonNullable.<List<String>>of(failures);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MigrationVariableValidationReportDtoAllOf migrationVariableValidationReportDtoAllOf = (MigrationVariableValidationReportDtoAllOf) o;
    return Objects.equals(this.failures, migrationVariableValidationReportDtoAllOf.failures);
  }

  @Override
  public int hashCode() {
    return Objects.hash(failures);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MigrationVariableValidationReportDtoAllOf {\n");
    sb.append("    failures: ").append(toIndentedString(failures)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

