/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.openapi.client.model;

import com.camunda.consulting.openapi.client.model.HistoricProcessInstanceQueryDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DeleteHistoricProcessInstancesDto
 */
public class DeleteHistoricProcessInstancesDtoTest {
    private final DeleteHistoricProcessInstancesDto model = new DeleteHistoricProcessInstancesDto();

    /**
     * Model tests for DeleteHistoricProcessInstancesDto
     */
    @Test
    public void testDeleteHistoricProcessInstancesDto() {
        // TODO: test DeleteHistoricProcessInstancesDto
    }

    /**
     * Test the property 'historicProcessInstanceIds'
     */
    @Test
    public void historicProcessInstanceIdsTest() {
        // TODO: test historicProcessInstanceIds
    }

    /**
     * Test the property 'historicProcessInstanceQuery'
     */
    @Test
    public void historicProcessInstanceQueryTest() {
        // TODO: test historicProcessInstanceQuery
    }

    /**
     * Test the property 'deleteReason'
     */
    @Test
    public void deleteReasonTest() {
        // TODO: test deleteReason
    }

    /**
     * Test the property 'failIfNotExists'
     */
    @Test
    public void failIfNotExistsTest() {
        // TODO: test failIfNotExists
    }

}
