/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.openapi.client.model;

import com.camunda.consulting.openapi.client.model.JobQueryDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SetJobRetriesDto
 */
public class SetJobRetriesDtoTest {
    private final SetJobRetriesDto model = new SetJobRetriesDto();

    /**
     * Model tests for SetJobRetriesDto
     */
    @Test
    public void testSetJobRetriesDto() {
        // TODO: test SetJobRetriesDto
    }

    /**
     * Test the property 'jobIds'
     */
    @Test
    public void jobIdsTest() {
        // TODO: test jobIds
    }

    /**
     * Test the property 'jobQuery'
     */
    @Test
    public void jobQueryTest() {
        // TODO: test jobQuery
    }

    /**
     * Test the property 'retries'
     */
    @Test
    public void retriesTest() {
        // TODO: test retries
    }

}
